### ISSUE TITLE
Possible typo "talking in the room"

### ISSUE THREAD

**Issue by falk-hueffner** [standardebooks/agatha-christie_the-murder-on-the-links#3]
in chapter-4.xhtml, there's the passage

> Poirot stood a moment talking in the room, then he stepped forward, [...]

While it is like this also in the scan, "talking" doesn't make a lot of sense here, and it seems fairly clear that it should be "taking in the room". This is also found in some other online versions such as https://archive.org/stream/agathachristie/Agatha%20Christie/English/Agatha%20Christie%20-%20Murder%20on%20the%20Links_djvu.txt .

**Comment by acabal** [comment]
Good catch, I've gone ahead and corrected it. Thanks!
